[workspace]
members = [
    "device",
    "fatfs",
    "kernel",
    "kernel-entry",
    "linux-syscall",
    "task_scheduler"
]
# default-members = ["kernel"]

[profile.release]
lto = true
debug = true